kind: Deployment
apiVersion: apps/v1
metadata:
  name: mssql-deployment
  labels:
    app: mssql1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: mssql1
  template:
    metadata:
      labels:
        app: mssql1
    spec:
      containers:
        - image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
          imagePullPolicy: IfNotPresent
          name: mssql
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: db
            initialDelaySeconds: 90
            timeoutSeconds: 30
          readinessProbe:
            tcpSocket:
              port: db
            initialDelaySeconds: 30
            timeoutSeconds: 30
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql1-secret
                  key: sapassword
          ports:
            - containerPort: 1433
              name: db
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mssql-data
      restartPolicy: Always
      

